version: '3.9'

services:
  postgres:
    image: postgres:17.4
    container_name: db_e_commerce_hm_client
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: client
    ports:
      - "5555:5432"
    volumes:
      - ./data:/var/lib/postgresql/data